language: node_js
install: npm install

jobs:
    include:
    - script: npm run test
      name: "Unit + Integration Node 10"
      node_js: "10"
    - script: npm run test
      name: "Unit + Integration Node 12"
      node_js: "12"
    - script: npm run lint
      name: "Linting"
      node_js: "12"
    - script: npm run ci-test
      name: "Coverage"
      node_js: "12"

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtlZ2FuJTNBbWF0cml4Lm9yZy8lMjFTdWR2aU9KbGltRHZyR2RGQ1klM0FtYXRyaXgub3Jn"
        on_success: change  # always|never|change
        on_failure: change
        on_start: never