steps:
  - label: ":eslint: Lint"
    command:
      - "npm install"
      - "npm run lint"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":jasmine: Tests Node 10"
    command:
      - "npm install"
      - "npm run build"
      - "npm run test"
    plugins:
      - docker#v3.0.1:
          image: "node:10"

  - label: ":jasmine: Tests Node 12"
    command:
      - "npm install"
      - "npm run build"
      - "npm run test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":nodejs: 12 :postgres: 11 :mocha: Postgres Test"
    plugins:
      - docker-compose#v2.1.0:
          run: testenv
          config:
            - .buildkite/docker-compose.postgres.yml

  - label: ":nyc: Coverage"
    command:
      - "npm install"
      - "npm run build"
      - "npm run ci-test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
